config/routes.rb
Epm::Application.routes.draw do

  resources :agencies

  resources :equipment_sets

  root 'events#dashboard'

  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    resources :roles, only: [:create, :destroy], shallow: true
    get 'map', on: :collection
    patch 'deactivate', on: :member
    get 'invite'
  end
  get 'me', to: 'users#me'
  get 'my_wards', to: 'users#my_wards'

  resources :events do
    get 'calendar', on: :collection
    get 'dashboard', on: :collection
    member do
      get 'who'
      get 'cancel', to: 'events#ask_to_cancel'
      patch 'cancel'
      patch 'approve'
      patch 'claim'
      patch 'unclaim'
      patch 'attend'
      patch 'unattend'
      patch 'invite'
      patch 'take_attendance'
    end
  end

  # for configurable_engine gem; it generates its own routes as well which are unused
  put 'settings', to: 'settings#update', as: 'settings'
  get 'settings', to: 'settings#show'

  resources :trees do
    get 'copy', on: :member
    get 'copy_location', on: :member
    get 'mine', on: :collection
    get 'closest', on: :collection
  end   

  get 'geocode', to: 'geocode#index'

end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable, :registerable, :confirmable, :recoverable, :rememberable, :trackable, :validatable

  strip_attributes

#  attr_accessor :signed_waiver
  attr_accessor :participate_in_picks
  attr_accessor :add_trees  
  
  validates :waiver, :acceptance => { :accept => true }, if: (:new_record? && :picks?)
  validates :email, :fname, :lname, :phone, presence: true

  enum ladder: {
    :yes => 1,
    :borrow => 2,
    :no => 3
  }

  def self.ladder_show_labels 
  {
    "has a ladder" => :yes,
    "can borrow a ladder from a neighbour" => :borrow,
    "does not have a ladder" => :no
  }
  end

  def self.ladder_labels 
  {
    "Yes" => :yes,
    "I can borrow one from a neighbour" => :borrow,
    "No" => :no
  }
  end

  def picks?
    participate_in_picks == "1"
  end

  def self.csv(users)
    CSV.generate force_quotes: true do |csv|
      csv << ['id', 'first name', 'last name', 'email', 'phone number', 'address', 'allow snail mail', 'joined', "events attended as #{Configurable.participant.indefinitize}", 'roles']
      users.each do |user|
        csv << [user.id, user.fname, user.lname, user.email, user.phone, user.address, user.snail_mail, user.created_at.to_date.to_s, user.num_participated_events, user.roles.map{|r| Configurable.send(r.name)}.join(', ')]
      end
    end
  end

  # this section identical to that in model event.rb
  acts_as_mappable
  attr_accessor :no_geocode # force geocoding to not happen. used for testing
  after_validation :geocode, if: "!no_geocode && address_changed? && address.present? && (lat.blank? || lng.blank?)"
  validates :lat, numericality: {greater_than_or_equal_to: -90, less_than_or_equal_to: 90}, allow_nil: true
  validates :lng, numericality: {greater_than_or_equal_to: -180, less_than_or_equal_to: 180}, allow_nil: true

  has_many :user_wards
  has_many :wards, through: :user_wards

  scope :by_name, -> { order :lname, :fname }
  scope :geocoded, -> { where.not lat: nil }
  scope :search, ->(q) {
    db = Rails.configuration.database_configuration[Rails.env]["adapter"]
    like = db == 'postgresql' ? 'ILIKE' : 'LIKE'
    name = db ==  'mysql2' ? "CONCAT(users.fname, ' ', users.lname)" : "(users.fname || ' ' || users.lname)"
    where("users.email #{like} ? OR #{name} #{like} ?", "%#{q}%", "%#{q}%")
  }
  scope :roleless, -> { where 'users.id NOT IN (SELECT DISTINCT user_id FROM roles)' }
  # todo: consider refactoring these to automatically have a scope for every role
  scope :admins, -> { joins("INNER JOIN roles ON roles.user_id = users.id AND roles.name = #{Role.names[:admin]}") }
  scope :coordinators, -> { joins("INNER JOIN roles ON roles.user_id = users.id AND roles.name = #{Role.names[:coordinator]}") }
  scope :participants, -> { joins("INNER JOIN roles ON roles.user_id = users.id AND roles.name = #{Role.names[:participant]}") }
  def self.coordinators_not_taking_attendance
    # get the ids of events needing attendance taken and more 3 days old (note: query is executed as a subquery of the next query)
    event_ids = Event.needing_attendance_taken.where("finish < ?", 3.days.ago).reorder(nil).select 'events.id'
    # get the coordinators of those events, orderded by how many events they haven't done attendance for
    coordinator_ids = Event.where("id IN (#{event_ids.to_sql})").group(:coordinator_id).reorder('COUNT(events.id) DESC').select(:coordinator_id).pluck :coordinator_id
    coordinators = User.where(id: coordinator_ids).to_a
    coordinator_ids.map{|uid| coordinators.find{|c| c.id == uid} }
  end
  scope :not_involved_in, ->(event) { where.not "users.id IN (#{EventUser.where(event_id: event.id).select(:user_id).to_sql})" }
  scope :interested_in_ward, ->(ward) { joins("INNER JOIN user_wards ON user_wards.user_id = users.id AND user_wards.ward_id = #{ward.id}") }
  scope :invitable_to, ->(event) {
    return none unless event.ward
    participants.interested_in_ward(event.ward).not_involved_in(event)
  }
  scope :no_shows, -> {
    joins("INNER JOIN event_users ON event_users.user_id = users.id AND event_users.status = #{EventUser.statuses[:no_show]}")
      .group('users.id')
      .reorder('MAX(event_users.updated_at) DESC, COUNT(users.id)')
  }
  def no_show_count
    event_users.where(status: EventUser.statuses[:no_show]).count
  end

  has_many :event_users, dependent: :destroy
  has_many :coordinating_events, -> { where.not(status: Event.statuses[:cancelled]) }, class_name: 'Event', foreign_key: 'coordinator_id'
  has_many :participated_events, -> { # events where a user was marked as having attended (and thus in the past and not cancelled)
      where('event_users.status' => EventUser.statuses[:attended]).where('events.status = ?', Event.statuses[:approved])
    }, through: :event_users, source: :event

  def events # where the user is a participant or the coordinator
    Event.not_cancelled
      .joins("LEFT JOIN event_users ON events.id = event_users.event_id AND event_users.status IN (#{EventUser.statuses_array(:attending, :attended).join(', ')})")
      .where("events.coordinator_id = ? OR event_users.user_id = ?", id, id)
      .distinct
  end

  def open_invites # upcoming events the user has been invited to
    Event.not_past.not_cancelled.joins(:event_users)
      .where(
        'event_users.status' => EventUser.statuses[:invited],
        'event_users.user_id' => id
      )
  end
  def potential_events # upcoming events where waitlisted or requested to attend
    Event.not_past.not_cancelled.joins(:event_users)
      .where(
        'event_users.status' => EventUser.statuses_array(:waitlisted, :requested),
        'event_users.user_id' => id
      )
  end
  def participating_events # upcoming events the participant plans to attend
    Event.not_past.not_cancelled.joins(:event_users)
      .where(
        'event_users.status' => EventUser.statuses[:attending],
        'event_users.user_id' => id
      )
  end

  has_many :roles, dependent: :destroy
  accepts_nested_attributes_for :roles
  attr_accessor :no_roles
  after_create :set_default_role, if: "roles.empty? && !no_roles" 
  def set_default_role
   if self.class.count == 1
      self.roles.create name: :admin
    elsif self.waiver? && self.picks?
      self.roles.create name: :participant
    end
  end
  def has_role?(role_name)
    !self.roles.find{|r| r.send "#{role_name}?" }.nil?
  end
  def has_any_role?(*roles)
    roles.each do |role|
      return true if has_role?(role)
    end
    false
  end

  def display_name
    n = "#{fname} #{lname}".strip
    n.present? ? n : '(no name given)'
  end

  def avatar(size = :small)
    sizes = {small: 48, large: 80}
    "http://gravatar.com/avatar/#{CGI.escape(Digest::MD5.hexdigest(email.downcase))}?s=#{sizes[size]}&d=mm"
  end

  def ability # allows checking permissions for this user rather than the current
    @ability ||= Ability.new(self)
  end

  def add_to_mailing_list # note: does not first check whether user is already on the mailing list
    return false unless self.valid? && email.present?
    return true unless Rails.env.production? # temporary solution to avoiding API calls
    Gibbon::API.throws_exceptions = false
    gb = Gibbon::API.new(ENV['mailing_list_api_key'])
    resp = gb.lists.subscribe( # http://apidocs.mailchimp.com/api/2.0/lists/subscribe.php
        id: ENV['mailing_list_id'],
        email: {email: email},
        merge_vars: {:FNAME => fname, :LNAME => lname},
        double_optin: false,
        send_welcome: true
      )
    !resp['email'].nil? && resp['status'] != 'error'
  end

  def coords
    (lat.present? && lng.present?) ? [lat, lng] : nil
  end

  private

    # this method identical to that in model event.rb
    def geocode
      geo = Geokit::Geocoders::MultiGeocoder.geocode address.gsub(/\n/, ', ')
      if geo.success
        self.lat, self.lng = geo.lat, geo.lng
      else
        errors.add(:address, 'Problem locating address')
      end
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  load_and_authorize_resource :user

  def me
    redirect_to current_user
  end
  def my_wards
    redirect_to edit_user_path(current_user, anchor: 'wards')
  end

  def index
    @users = User.by_name
    @q = params['q'] ? params['q'].strip : nil
    @users = @users.search(@q) if @q.present?
    show_only = params['show_only']
    if show_only.present? && User.respond_to?(show_only.downcase)
      @show_only = show_only
      @users = @users.send(show_only.downcase)
    end

    respond_to do |format|
      format.html { @users = @users.page(params[:page]).per(20) }
      format.csv { send_data User.csv(@users) }
    end
  end

  def map
    @layers = [
      {
          points: User.participants.geocoded.select('lat, lng'),
          name: Configurable.participant.pluralize.titlecase
      },
      {
          points: User.coordinators.geocoded.select('lat, lng'),
          name: Configurable.coordinator.pluralize.titlecase
      }
    ].reject{|h| h[:points].length < 10}
    codes = []
    @layers.each do  |h|
      n = 0
      while codes.include? h[:name][0..n]
        n+= 1
      end
      h[:code] = h[:name][0..n]
      codes << h[:code]
    end
  end

  def destroy
    if @user.destroy
      redirect_to action: "index", notice: 'User deleted.'
    else 
      redirect_to @user, notice: 'User not deleted.'
    end
  end

  def show
    @past_coordinating = @user.coordinating_events.past
  end

  def edit
  end

  def update
    if params['commit'] && params['commit'].downcase == 'cancel'
      redirect_to @user, notice: 'Changes not saved.'
    elsif @user.update params.require(:user).permit(:fname, :lname, :email, :phone, :address, :snail_mail, :lat, :lng, :home_ward, :participate_in_picks, :add_trees, :ladder, :password_confirmation, :waiver, :admin_notes, :do_not_contact_reason, ward_ids: [])
      # note the params permitted above need to also be listed in the registrations controller
      redirect_to @user, notice: 'Profile was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def deactivate
    @user.roles.each do |role|
      role.destroyed_by_self = current_user == @user
      role.destroy
    end
    if @user.roles.reload.none?
      flash[:notice] = 'Your account has been deactivated.'
    else
      flash[:notice] = 'Your account was unable to be deactivated.'
    end
    redirect_to @user
  end

  def invite 
    @user = User.find(params['user_id'])
    if params['event_id']
      @event = Event.find(params['event_id'])
      eu = @event.event_users.create user: @user, status: :invited
      if eu.valid?
        Invitation.create event: @event, user: @user, send_by: Time.zone.now
      end
      redirect_to @user, notice: 'User invited.'
    else
      @events = Event.accepting_participants
          #.joins("LEFT JOIN event_users ON event_users.event_id = events.id")
          #.where.not("event_users.user_id = " + @user.id.to_s)
          #.group("events.id")
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

  <%= render 'shared/errors', thing: @user %>

  <%= render 'form_inner', f: f, user: @user %>

  <%= cancel %>
  <%= submit 'Save Profile' %>

<% end %>

app/views/users/_form_inner.html.erb
<%= start_cols %>
<% if action_name == "new" %>
  <fieldset>
    <legend>How do you want to participate in Not Far From the Tree?</legend>
    <label style="margin:0 0.7em"><%= f.check_box  :participate_in_picks %> I want to participate in NFFTT picks</label>
    <br />
    <label style="margin:0 0.7em"><%= f.check_box  :add_trees %> I want to add trees to NFFTT's tree database</label>
  </fieldset>
<% end %>

<h1>Your NFFTT Login Info</h1>
<fieldset>
  <legend>Name <%= required %></legend>
  <%= f.text_field :fname, placeholder: 'First' %> &nbsp; &nbsp; &nbsp;
  <%= f.text_field :lname, placeholder: 'Last' %>
</fieldset>

<% if user.new_record? %>
  <fieldset>
    <legend>Password  <%= required %></legend>
    <%= f.password_field :password, placeholder: 'password' %><br>
    <%= f.password_field :password_confirmation, placeholder: 'repeat password' %>
  </fieldset>
<% end %>

<%= end_cols %>


<div id="contact_information" class="block">
<%= start_cols %>


  <h1>Contact Information</h1>
  <div class="field">
    <%= f.label :email %> <%= required %><br>
    <%= f.email_field :email %>
  </div>

  <div class="field">
    <%= f.label :phone %>  <%= required %><br>
    <%= f.phone_field :phone %>
  </div>

    <% if user.new_record? %>
      <div>
      <label style="font-weight:normal">
        <%= check_box_tag :add_to_mailing_list, true, false %>
        Subscribe me to the Not Far From The Tree mailing list
      </label>
      </div>
      <br />
      You can tell me about picks by:
      <div style="margin-left: 20px">
        <label style="font-weight:normal">
          <%= check_box_tag :can_email, true, user.new_record? %>
          <b>Email</b>
        </label>
      </div>
      <div style="margin-left: 20px">
        <label style="font-weight:normal">
          <%= check_box_tag :can_mail, true, user.new_record? %>
          <b>Mail</b>
        </label>
      </div>
      <div style="margin-left: 20px">
        <label style="font-weight:normal">
          <%= check_box_tag :can_phone, true, user.new_record? %>
          <b>Phone</b>
        </label>
      </div>
    <% end %>  

<%= next_col %>

<p style="font-style:italic"> We need your address to match you to close-by picks and to help you quickly add trees from your own property. </p>
<script language="">
  var active_wards = <% if Configurable.active_wards.present? %> <%=Configurable.active_wards.split(",").to_json.html_safe %> <% else %> [] <% end %>
  $(document).ready(function () {
    <% if action_name == "new" %>
      $("#ladderSection").hide();
      $("#propertyNotesSection").hide();
    <% end %>
      $("#user_add_trees").change(function (evt) {
          var isChecked = $(evt.currentTarget).prop("checked");
          if (!!isChecked) {
            $("#ladderSection").show();
            $("#propertyNotesSection").show();
          } else {
            $("#ladderSection").hide();
            $("#propertyNotesSection").hide();
          }
      })

      $("[name='user[home_ward]']").change(function (evt) {
        var ward = evt.currentTarget.value;
        $("#ward_"+ward)[0].checked = true;
        if ($.inArray(ward.toString(), active_wards) != -1) {
          $("#inactive_ward_message").hide()
        }
        else {
         $("#inactive_ward_message").show() 
        }
      });
      $("#inactive_ward_message").hide()
  });
</script>
  <div>
    <%= f.label :home_ward, style: 'font-weight:normal' %>
    <%= f.collection_select :home_ward, Ward.all, :id, :name, include_blank: true %>
    <span class="hint"><%= link_to 'ward map', 'http://app.toronto.ca/wards/jsp/wards.jsp' %></span>
    <div id="inactive_ward_message" class="note">
        Aw! We don't serve your ward yet, but please go ahead and sign up! We're expanding every season, and we'll be sure to email you when we land in your ward!
    </div>
  </div>


<%= render layout: 'shared/address_form', locals: { f: f } do %>
  <div><%= f.check_box :snail_mail %> <%= f.label :snail_mail, style: 'font-weight:normal' %></div>
<% end %>
<% content_for :js_ready do %>
  $("#bad_geocode").hide();
<% end %>
<div id="bad_geocode" class="note">
  We couldnt find that address on a map. Could you put directions below and a street address (e.g. 123 Yonge St. Toronto, ON) above? 
</div>

<fieldset id="propertyNotesSection">
<div class="field">
  <%= f.label :propertynotes, "Property Notes" %>  <%= required %><br>
  <%= f.text_area :propertynotes %>
</div>
</fieldset>
<fieldset id="ladderSection">
  <legend>Do have a ladder on the property?</legend>
    <label style="margin:0 0.7em"><%= f.radio_button :ladder, :yes %>Yes</label>
    <label style="margin:0 0.7em"><%= f.radio_button :ladder, :borrow %>I can borrow one from a neighbour</label>
    <label style="margin:0 0.7em"><%= f.radio_button :ladder, :no %>No</label>
</fieldset>

<%= end_cols %>

</div>

<% if Ward.any? %>
  <fieldset id="wards">
    <legend>My Wards</legend>
    <p class="hint">
      You will be invited by email to <%= Configurable.event.pluralize %> in the wards you select.<br>
      Wards in <span style="color:gray">grey</span> will have few/no <%= Configurable.event.pluralize %> this year, but may have more in the future.
    </p>
    <%= hidden_field_tag "user[ward_ids][]" %>
    <%= start_cols %>

    <%= start_cols %>
    <% Ward.all.each_with_index do |ward, i| %>
      <%= next_col if i % 22 == 0 %>
      <label<%= ' style="color:gray"'.html_safe unless ward.active? %>>
        <%= check_box_tag "user[ward_ids][]", ward.id, @user.ward_ids.include?(ward.id), id: "ward_#{ward.id}" %>
        <%= ward.name %>
      </label>
    <% end %>
    <%= end_cols %>

    <%= next_col %> 

    <a href="http://app.toronto.ca/wards/jsp/wards.jsp" style="display:block;text-align:right">
      <img src="http://www.toronto.ca/wards2000/images/wards_keymap.gif" width="602" height="334" alt="map of Toronto wards">
      <br>
      Check which ward you live in
    </a>

    <%= end_cols %>
  </fieldset>

<% if current_user.present? %>
  <% if current_user.has_role?(:admin) %>
    <div class="field">
      <%= f.label :admin_notes %> <br>
      <%= f.text_area :admin_notes %>
    </div>
  <% end %>
<% end %>


<% if action_name == "edit" && (current_user.has_role?(:admin) || current_user.id == @user.id) %>
    <div class="field">
      If you do not want to be contacted anymore, please explain why:<br>
      <%= f.text_area :do_not_contact_reason %>
    </div>
<% end %>


<% end %>

app/views/users/_user.html.erb
<%= content_tag (tag ||= 'div'), class: 'user', style: "background-image:url('#{user.avatar}')" do %>
  <%= link_to_if can?(:show, user), user.display_name, user %>
  <%
    desc = ''
    desc += (yield || '').strip if block_given?
  %>
  <%= content_tag(:p, desc) if desc.present? %>
<% end %>

app/views/users/_users.html.erb
<ul class="users">

  <% users.each do |user| %>

    <%= render 'users/user', user: user, tag: 'li' %>

  <% end %>

</ul>

app/views/users/edit.html.erb
<% title "Edit #{@user == current_user ? 'My ' : ''}Profile" %>

<%= render 'form' %>

app/views/users/index.html.erb
<% if can? :map, User %>
  <% content_for :header do %>
    <%= link_to 'Map', map_users_path %>
  <% end %>
<% end %>

<%= form_tag users_path, method: :get do %>
  <%= select_tag :show_only, options_for_select(Role.names.map{|n, v| [Configurable.send(n).pluralize.titlecase, n.pluralize]}.unshift(['Everyone', nil]) << ['No roles', 'roleless'] << ['No shows', 'no_shows'], @show_only) %>
  <% content_for :js_ready do %>
    $('select').change(function(){
      $(this).closest('form').submit();
    });
  <% end %>
  <%= text_field_tag :q, @q, placeholder: 'name or email' %>
  <%= submit 'Search' %>
<% end %>

<%= link_to 'Export these users', users_path(format: 'csv', show_only: params[:show_only], q: params[:q]) %>


<% if @users.any? %>
  <h2><%= pluralize @users.total_count, 'User' %></h2>
  <%= paginate @users %>
  <%
     if @users.length > 5
      switch_col = @users.length / 2
      switch_col += 1 if @users.length.odd?
    end
  %>
  <%= start_cols %>
  <ul class="users">
    <% @users.each_with_index do |user, i| %>
      <%= "</ul>#{next_col}<ul class=\"users\">".html_safe if defined?(switch_col) && switch_col == i %>
      <%= render layout: 'user', locals: {user: user, tag: 'li'} do %>
        <% if @q.present? %>
          <%= user.email %>
        <% elsif @show_only == 'no_shows' %>
          Missed <%= pluralize user.no_show_count, 'event' %>.
        <% elsif !@show_only %>
          <%= user.roles.map {|r| Configurable.send(r.name).titlecase}.join ', ' %>
        <% end %>
      <% end %>
    <% end %>
  </ul>
  <%= end_cols %>
  <%= paginate @users %>
<% else %>
  <p>No users found.</p>
<% end %>

app/views/users/invite.html.erb
<ol class="open_events">
  <% @events.each do |event| %>
  	
    <% coords = event.coords(current_user) %>
    <li<%= " data-lat=\"#{coords[0]}\" data-lng=\"#{coords[1]}\"".html_safe if coords %> style="margin-top: 20px; list-style: none">
      <%= link_to event.display_name(current_user), event %>
      <% if event.start.present? %>
        <small><%= relative_time event %></small>
      <% end %>
     <%= link_to "Invite to #{Configurable.event.titlecase}", user_invite_path(event_id: event.id), {class: "button"} %>
    </li>
  <% end %>
</ol>

app/views/users/map.html.erb
<% title 'Map' %>

<% if @layers.any? %>

  <div>
    <% @layers.each do |h| %>
      <div style="margin:0.2em 0"><div class="mapicon"><%= h[:code] %></div> <%= h[:name] %></div>
    <% end %>
  </div>

  <div id="map" class="map" style="height:45em;margin-top:1em"></div>
  <% content_for :js_ready do %>
    var map = make_map('map', true);
    <% @layers.each do |h| %>
      var <%= h[:code] %>_icon = L.divIcon({html: '<%= h[:code] %>', className: 'mapicon', iconSize: [20,20]});
      $([<%= h[:points].map{|u| "[#{u.lat.round(2)}, #{u.lng.round(2)}]"}.join(',') %>]).each(function(){
        L.marker(this, {icon: <%= h[:code] %>_icon}).addTo(map);
      });
    <% end %>
    <%
      everybody = @layers.map{|h| h[:points]}.flatten
      lats = everybody.map{|u| u.lat}
      lngs = everybody.map{|u| u.lng}
    %>
    map.fitBounds([[<%= lats.min %>, <%= lngs.min %>], [<%= lats.max %>, <%= lngs.max %>]], {padding: [20, 20]});
  <% end %>
  Note: Locations are approximate.

<% else %>

  <p>There are not enough users to display a map.</p>

<% end %>

app/views/users/show.html.erb
<%
  tit = @user.display_name
  tit = "Inactive: #{tit}" if @user.roles.empty?
  title tit
%>

<% content_for :header do %>
  <% if can? :update, @user %>
    <%= link_to 'Edit', edit_user_path(@user) %>
  <% end %>
  <% if can? :destroy, @user %>
    <%= link_to 'Delete', user_path(@user), method: :delete, data: {confirm: 'Are you sure you want to delete this account?'}  %>
  <% end %>
  <% if can? :invite, @user %>
    <%= link_to 'Invite to Event', user_invite_path(@user) %>
  <% end %>
  <% if @user.id == current_user.id %>
    <%= link_to 'Change my password', edit_user_registration_path %>
    <% if @user.roles.any? && can?(:deactivate, @user) %>
      <%= link_to 'Deactivate my account', deactivate_user_path(current_user), method: :patch, data: {confirm: 'Are you sure you want to deactivate your account?'} %>
    <% end %>
  <% end %>
<% end %>

<%= image_tag @user.avatar('large'), size: '80x80', alt: 'profile photo', class: 'avatar' %>

<div id="roles">
  <%= 'Role'.pluralize @user.roles.count %>:
  <% if @user.roles.any? %>
    <%=
      @user.roles.map do |role|
        outp = Configurable.send(role.name).titlecase
        if can?(:destroy, role) && current_user.has_role?(:admin)
          outp += button_to 'x', role, method: :delete, title: 'remove this role', class: 'danger', data: {confirm: 'Are you sure you want to remove this role?'}
        end
        outp
      end.to_sentence.html_safe
    %>
  <% else %>
    None
  <% end %>
  <% if can? :create, Role %>
    <% other_roles = Role.names.reject{|n, v| @user.roles.find{|r| r.name == n} } %>
    <% if other_roles.any? %>
      <%= form_for [@user, @user.roles.build], html: {style: 'display:inline'} do |f| %>
        <%= f.select :name, options_for_select(other_roles.map{|n,v|[Configurable.send(n).titlecase, n]}.unshift(['Add Role', nil])) %>
        <%= submit 'Add' %>
      <% end %>
    <% end %>
  <% end %>
</div>

<p>Wards: <%= @user.wards.any? ? @user.wards.map{|w|w.name}.to_sentence : 'none' %>.</p>

<p>Joined <%= @user.created_at.strftime "%B %d %Y" %>.</p>

<%= clear %>

<% if can? :read_contact, @user %>
  <div>
    <h2>Contact Information</h2>
    <p><%= mail_to @user.email %></p>
    <% if @user.phone %>
      <%= link_to @user.phone, "tel:#{@user.phone}" %>
    <% end %>
    <% if @user.address %>
      <p>
        <%= with_br @user.address %><br>
        <small>Snail mail <%= 'not' unless @user.snail_mail %> allowed</small>
      </p>
    <% end %>
  </div>
<% end %>

<% if can? :read_attendance, @user %>

  <% if @past_coordinating.any? %>
    <div id="past_coordinating">
      <h2>Past <%= Configurable.event.pluralize.titlecase %> Run</h2>
      <%= render 'events/events', events: @past_coordinating %>
    </div>
  <% end %>

  <% if @user.event_users.any? %>
    <ol class="unordered">
      <% @user.event_users.joins(:event).order('events.start asc').each do |eu| %>
        <li>
          <%= link_to eu.event.display_name(current_user).to_s + "  " + date(eu.event.start).to_s, eu.event %> (<%=eu.event.status.capitalize %>) <span class="label <%=eu.status %>"> <%=event_user_status(eu.status) %></span>
            <% if can?(:unattend, eu.event) && eu.status == "attending" && !eu.event.past? %>
              <%= link_to "Cancel their Attendance", unattend_event_path(eu.event,user_id: @user.id), method: :patch %>
            <% end %>
        </li>
      <% end %>
    </ol>
  <% end %>

<% end %>

<% if current_user.has_role?(:admin) %>

    <% @otrees = Tree.where({owner: @user}) %>
    <% puts @otrees.to_yaml %>
    <% if @otrees.any? %>
      <h2> Trees on their Property </h2>
      <ol class="unordered">
        <% @otrees.each do |t| %>
          <li>
            <%= link_to t.species, t %>
          </li>
        <% end %>
      </ol>
    <% end %>


    <% @strees = Tree.where({submitter: @user}) %>
    <% if @strees.any? %>
      <h2> Trees they Manage </h2>
      <ol class="unordered">
        <% @strees.each do |t| %>
          <li>
            <%= link_to t.species + " - " + t.owner.address, t %>
          </li>
        <% end %>
      </ol>
    <% end %>

<% end %>


<% if current_user.has_role?(:admin) %>
  <p>
    <b>Admin Notes: </b>
  </p>
  <p>
    <%=@user.admin_notes || "None" %> <br>
  </p>
<% end %>


<% if (current_user.has_role?(:admin) || current_user.id == @user.id) && @user.do_not_contact_reason.present? %>
    <div class="field">
      <b>Do Not Contact Reason</b>:<br>
      <%=@user.do_not_contact_reason %>
    </div>
<% end %>