config/routes.rb
Epm::Application.routes.draw do

  resources :agencies

  resources :equipment_sets

  root 'events#dashboard'

  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    resources :roles, only: [:create, :destroy], shallow: true
    get 'map', on: :collection
    patch 'deactivate', on: :member
    get 'invite'
  end
  get 'me', to: 'users#me'
  get 'my_wards', to: 'users#my_wards'

  resources :events do
    get 'calendar', on: :collection
    get 'dashboard', on: :collection
    member do
      get 'who'
      get 'cancel', to: 'events#ask_to_cancel'
      patch 'cancel'
      patch 'approve'
      patch 'claim'
      patch 'unclaim'
      patch 'attend'
      patch 'unattend'
      patch 'invite'
      patch 'take_attendance'
    end
  end

  # for configurable_engine gem; it generates its own routes as well which are unused
  put 'settings', to: 'settings#update', as: 'settings'
  get 'settings', to: 'settings#show'

  resources :trees do
    get 'copy', on: :member
    get 'copy_location', on: :member
    get 'mine', on: :collection
    get 'closest', on: :collection
  end   

  get 'geocode', to: 'geocode#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :event_trees
  belongs_to :equipment_set
  belongs_to :agency
  has_many :trees, :through => :event_trees 
  accepts_nested_attributes_for :event_trees
  strip_attributes

  def self.csv(events)
    # exports events; adds info for number of people for each event user status, i.e. how many attended, how many were waitlisted, etc.
    CSV.generate force_quotes: true do |csv|
      eu_statuses = EventUser.statuses.keys.map{|s| "#{Configurable.participant.pluralize} #{s}"}
      csv << ['id', 'name', 'status', 'created', 'updated', 'start', 'finish', 'description', 'notes', Configurable.coordinator, 'address', "min #{Configurable.participant.pluralize}", "max #{Configurable.participant.pluralize}"] + eu_statuses
      events.each do |event|
        row = [event.id, event.name, event.status, event.created_at, event.updated_at, event.start, event.finish, event.description, event.notes, event.coordinator ? event.coordinator.display_name : nil, event.address, event.min, event.max]
        eus = event.event_users.group('event_users.status').count
        EventUser.statuses.each{|status, status_id| row << (eus[status_id] || 0) }
        csv << row
      end
    end
  end

  def coordinator_id=(val)
    # this was needed due to radio button converting 'nil' value to 'on' to 0
    val = nil unless val.to_i > 0
    super val
  end

  def changed_significantly?
    # todo: remove lat+lng from this and test separataly via removal or addition of coords or distance change > n
    ['start', 'finish', 'name', 'description', 'address', 'lat', 'lng'].each do |attr|
      return true if self.send(attr) != prior[attr]
    end
    false
  end

  attr_accessor :prior
  def track
    self.prior = attributes
    ['past?', 'awaiting_approval?'].each do |meth|
      self.prior[meth] = send(meth)
    end
  end

  enum status: [:proposed, :approved, :cancelled]

  def can_edit_attribute?(attribute, user)
    return false unless user.ability.can?(:edit, self)
    return true if user.has_role?(:admin)
    return true if user.has_role?(:coordinator) && ((coordinator.present? && coordinator == user) || coordinator.blank?)
    return false unless [:start, :finish].include?(attribute)
    #proposed? || start.blank?
  end

  def can_edit_something?(user)
    [:name, :start, :finish, :notes, :description, :address, :lat, :lng, :ward, :hide_specific_location, :min, :max, :coordinator].each do |attr|
      return true if can_edit_attribute? attr, user
    end
    false
  end

  validate :must_not_be_empty
  def must_not_be_empty
    if start.blank? && name.blank? && description.blank? && address.blank? && !coords
      errors.add(:base, 'An event must have a name, description, date, or address')
    end
  end

  validate :must_start_before_finish
  validates :finish, presence: true, if: "start.present?"
  def must_start_before_finish
    if start.present? && finish.present? && start > finish
      errors.add(:finish, 'must be after the start')
    end
  end

  before_validation do |event|
    event.finish = nil if event.start.blank?
    # don't allow saving with only one of lat, lng; must be neither or both
    event.lat = nil if event.lng.blank?
    event.lng = nil if event.lat.blank?
  end

  def min=(val)
    val = 0 if val.blank?
    super(val)
  end
  validate :max_must_be_at_least_min
  def max_must_be_at_least_min
    if max.present? && max < min
      errors.add(:max, 'must be greater than the minimum, or blank')
    end
  end

  belongs_to :ward

  # allow for adding a reason for cancelling an event, with separate fields for admin/coordinator and participants
  attr_accessor :cancel_notes, :cancel_description
  def cancel_notes=(str)
    str = str.strip unless str.nil?
    if str.present?
      self.notes = "Cancelled because: #{str}\n\n#{notes}".strip
      @cancel_notes = str
    end
  end
  def cancel_description=(str)
    str = str.strip unless str.nil?
    if str.present?
      self.description = "Cancelled because: #{str}\n\n#{description}".strip
      @cancel_description = str
    end
  end
  def cancel(reasons = {})
    update reasons.merge(status: :cancelled)
    Invitation.where(event_id: id).destroy_all
  end

  has_many :event_users, dependent: :destroy
  has_many :participants, -> { where 'event_users.status' => EventUser.statuses_array(:attending, :attended) }, through: :event_users, source: :user
  has_many :waitlisted, -> { where('event_users.status' => EventUser.statuses[:waitlisted]).order('event_users.updated_at') }, through: :event_users, source: :user
  has_many :no_shows, -> { where 'event_users.status' => EventUser.statuses['no_show'] }, through: :event_users, source: :user
  belongs_to :coordinator, class_name: 'User'
  def users # i.e. participants and the coordinator
    people = participants.to_a
    people << coordinator if coordinator
    people
  end

  # this section identical to that in model user.rb
  acts_as_mappable
  attr_accessor :no_geocode # force geocoding to not happen. used for testing
  after_validation :geocode, if: "!no_geocode && address_changed? && address.present? && (lat.blank? || lng.blank?)"
  validates :lat, numericality: {greater_than_or_equal_to: -90, less_than_or_equal_to: 90}, allow_nil: true
  validates :lng, numericality: {greater_than_or_equal_to: -180, less_than_or_equal_to: 180}, allow_nil: true

  default_scope { order :start }
  scope :with_date, -> { where 'start IS NOT NULL AND finish IS NOT NULL' }
  scope :past, -> { where('finish < ?', Time.zone.now).reorder('finish DESC') }
  scope :not_past, -> { where 'start IS NULL OR finish > ?', Time.zone.now }
  scope :participatable_by, ->(user) { # checks user for participatablility, assumed already checking that the events for participatability
    where.not("id IN (SELECT event_id FROM event_users WHERE user_id = ? AND status IN (?))", user.id, EventUser.statuses_array(:attending, :waitlisted, :requested, :denied))
      .where.not(coordinator_id: user.id)
      .distinct
  }
  scope :coordinatorless, -> { where coordinator: nil }
  scope :dateless, -> { where start: nil }
  #scope :byStatus -> (listofstatuses) { where(status: listofstatuses) }
  scope :participatable, -> { where.not(start: nil).where.not(coordinator_id: nil).where('events.status = ?', statuses[:approved]) }
  scope :not_cancelled, -> { where 'events.status != ?', statuses[:cancelled] }
  scope :awaiting_approval, -> { not_past.where 'events.status = ? AND coordinator_id IS NOT NULL AND start IS NOT NULL', statuses[:proposed] }
  scope :needing_participants, -> { participatable.not_past.where(below_min: true) }
  scope :accepting_participants, -> { participatable.not_past.where(reached_max: false) }
  scope :accepting_not_needing_participants, -> { accepting_participants.where(below_min: false) }
  scope :needing_attendance_taken, -> { participatable.past.joins("INNER JOIN event_users ON event_users.event_id = events.id AND event_users.status = #{EventUser.statuses[:attending]}").distinct }
  scope :in_month, ->(year, month) { # can pass in integers or strings which are integers
    month ||= ''
    year ||= ''
    unless (1..12).include?(month.to_i) && year.to_s.length == 4
      month = Time.zone.now.month
      year = Time.zone.now.year
    end
    start = Time.zone.parse "#{year}-#{month}-01"
    finish = month.to_i < 12 ? start.change(month: (start.month + 1)) : start.change(month: 1, year: (start.year + 1))
    where("start >= ? AND start < ?", start, finish)
  }
  scope :will_happen_in_two_days, -> {
    next_day = Time.zone.now + 1.day
    participatable.where('start > ? AND start < ?', next_day, (next_day + 1.day))
  }

  attr_reader :start_day, :start_time_12, :start_time_p
  attr_accessor :time_error
  before_validation do |event|
    errors.add(:start_time_12, 'Start time must be in the format ##:##') if event.time_error
    # todo. this should be added to start_time_12 rather than :base, but that's no good as "start time 12" is a poor name for users. fix
  end
  def assign_attributes(attrs)
    # if inputing start in parts (day and time), then combine them
    start_day = attrs.delete(:start_day)
    start_time = attrs.delete(:start_time_12)
    if start_time.present? && !(start_time.strip =~ /1?[0-9](:[0-9]{2})?/)
      start_time = nil
      self.time_error = true
    end
    start_time_p = (attrs.delete(:start_time_p) || 'AM').upcase.gsub('.', '')
    attrs[:start] = "#{start_day} #{start_time} #{start_time_p}" if attrs[:start].blank? && start_day.present? && start_time.present?
    # this is needed because during mass assignment, we can't guarantee that :start will be set before :duration
    dur = attrs.delete(:duration)
    super(attrs)
    self.duration = dur
  end
  def start_time_12 # start time using 12-hour clock
    start.present? ? start.strftime('%l:%M').strip : nil
  end
  def start_time_p
    start.present? ? start.strftime('%p') : nil
  end
  def duration=(timespan)
    if start.present? && timespan.present? && timespan.to_i > 0
      self.finish = start + timespan.to_i
    else
      nil
    end
  end
  def duration
    (start.present? && finish.present?) ? (finish - start).round : nil
  end
  def duration_hours
    duration.present? ? (duration / 3600) : nil
  end
  def self.default_time
    '5:00 PM'
  end

  def past?
    finish.present? ? finish < Time.zone.now : nil
  end
  def time_until
    start.present? ? start - Time.zone.now : nil
  end
  def hours_until
    start.present? ? (time_until / 1.hour).round : nil
  end

  def awaiting_approval?
    !past? && proposed? && coordinator && start
  end

  include ActionView::Helpers::TextHelper # needed for truncate()
  def display_name(user = nil)
    return name if name.present?
    return truncate(description, length: 50, separator: ' ') if description.present?
    if address.present? && (!hide_specific_location || (user && user.ability.can?(:read_specific_location, self)) )

app/models/tree.rb
class Tree < ActiveRecord::Base


  before_validation :check_species

  strip_attributes

  belongs_to :owner, class_name: "User"
  belongs_to :submitter, class_name: "User"
  has_many :event_trees
  has_many :events, :through => :event_trees
  accepts_nested_attributes_for :owner

  acts_as_mappable through: :owner

  attr_accessor :species_other

  enum keep: {
    :yes => 0,
    :abit => 1,
    :no => 2
  }


  enum relationship: {
    :propertyowner => "propertyowner",
    :friend => "friend",
    :tenant => "tenant"
  }

  def self.relationship_labels 
  {
    :propertyowner => "property owner",
    :friend => "friend",
    :tenant => "tenant"
  }
  end

  def self.keep_labels 
  {
    "Yes" => :yes,
    "Yes, but less than 1/3" => :abit,
    "No" => :no
  }
  end

  def self.keep_result_labels 
  {
    "1/3" => :yes,
    "less than 1/3" => :abit,
    "none" => :no
  }
  end

  enum height: {
    :lt1 => 1,
    :bt1n2 => 2,
    :bt2n3 => 3,
    :gt3 => 4
  }

  def self.height_labels
  {
    "> 3 storeys (> 9 metres, 30 feet)" => :gt3,
    "2-3 storeys (20-30 feet, 6-9 metres)" => :bt2n3,
    "1 - 2 storeys (10-20 feet, 3-6 metres)" => :bt1n2,
    "< 1 storey (< 10 feet, 3 metres)" => :lt1
  }
  end

  def self.types
    ["Apple","Apricot","Cherry","Crabapple","Elderberry","Ginkgo","Grape","Mulberry","Pawpaw","Peach","Pear","Persimmon","Plum","Quince","Serviceberry"]
  end

  def check_species
    if self.species.blank? && self.species_other.present?
      self.species = self.species_other
    end
  end 

  def self.closest(origin, ids, page)
    @page = 1
    if page.present? && page.to_i > 1
      @page = page.to_i
    end
    @trees = Tree.joins(:owner).by_distance(:origin => origin).where.not({'trees.id' => ids}).page(@page).per(10)
  end

  scope :search, ->(q) {
    db = Rails.configuration.database_configuration[Rails.env]["adapter"]
    like = db == 'postgresql' ? 'ILIKE' : 'LIKE'
    joins(:owner).where("trees.subspecies #{like} ? OR trees.species #{like} ? OR users.address #{like} ?", "%#{q}%", "%#{q}%", "%#{q}%")
  }
  
end

app/controllers/trees_controller.rb
class TreesController < ApplicationController
  # before_action :set_tree, only: [:show, :edit, :update, :destroy]

  load_and_authorize_resource :tree, except: :create
  authorize_resource :tree, only: :create
  authorize_resource :user
  # authorize_resource :tree

  # GET /trees
  def index
    @page = 1
    if params["page"].present?
      @page = params["page"]
    end
    @q = params['q'] ? params['q'].strip : nil   
    if @q.present?
      @trees = Tree.search(@q).page(@page).per(20)
    else 
      @trees = Tree.all().page(@page).per(20)
    end
  end

  def mine
    @page = 1
    if params["page"].present?
      @page = params["page"]
    end
    @isowner = Tree.where({owner_id: current_user.id })
    @issubmitter = Tree.where({submitter_id: current_user.id })
  end

  # GET /trees/1
  def show
    @events = EventTree.where({tree_id: @tree.id}) #.order(:start)
  end

  # GET /trees/new
  def new
    #render text: current_user.to_yaml
    #return
    @tree.owner = current_user
    #@tree.owner_id = current_user.id
  end

  # GET /trees/1/edit
  def edit
  end

  # GET /trees/1/copy
  def copy
    @new_tree = @tree.dup
    @new_tree.save
    @tree = nil
    @tree = @new_tree
    redirect_to action: 'edit', id: @tree.id
  end

  # GET /trees/1/copy_location
  def copy_location
    @new_tree = Tree.new
    @new_tree.owner = @tree.owner
    if @tree.owner_id != current_user.id
      @new_tree.submitter = current_user
    else 
      @new_tree.relationship = "propertyowner"
    end

    @new_tree.save
    redirect_to action: 'edit', id: @new_tree.id
  end

  def closest 
    @add = true
    @page = 1
    if params['page'].present? && params['page'].to_i > 1
      @page = params['page'].to_i
    end
    if params['ids'].blank?
      params['ids'] = []
    end
    @trees = Tree.closest([params['lat'],params['lng']], params['ids'], @page)
    render :_formlist, layout: false
  end

  # POST /trees
  def create
    @tree = Tree.new tree_params
    owner_params = params.require(:tree).permit(owner_attributes: [:id, :fname, :lname, :email, :phone, :ladder, :contactnotes, :propertynotes, :home_ward, :address, :lat, :lng])
    @tree.owner = User.find(owner_params["owner_attributes"]["id"].to_i)
    @tree.owner.attributes = owner_params["owner_attributes"]

    if @tree.owner.changed?
      # check if the name has changed, if so, create a new user
      if (@tree.owner.fname_changed? || @tree.owner.lname_changed?) && @tree.owner.email_changed?
        existing_user = User.where({ email: @tree.owner.email, address: @tree.owner.address})
        if existing_user.count > 0
          @tree.owner_id = existing_user.first.id
          @tree.submitter_id = current_user.id
        else 
          new_user_hash = @tree.owner.attributes
          new_user_hash.delete('id')
          new_user_hash.delete('confirmation_sent_at')
          new_user_hash.delete('confirmation_token')
          new_user_hash.delete('confirmed_at')
          new_user_hash.delete('current_sign_in_at')
          new_user_hash.delete('current_sign_in_ip')
          new_user_hash['created_at'] = DateTime.now
          new_user_hash['password'] = Devise.friendly_token.first(8)
          new_user = User.new(new_user_hash)
          new_user.skip_confirmation!
          new_user.save
          @tree.owner_id = new_user.id
          @tree.submitter_id = current_user.id
        end
      end
    end

    if @tree.save
      redirect_to @tree, notice: 'Tree was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /trees/1
  def update
    if @tree.update(tree_params)
      redirect_to @tree, notice: 'Tree was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /trees/1
  def destroy
    @tree.destroy
    redirect_to trees_url, notice: 'Tree was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # def set_tree
    #   @tree = Tree.find(params[:id])
    # end

    # Only allow a trusted parameter "white list" through.
    def tree_params
      params.require(:tree).permit(:height, :species, :species_other, :subspecies, :relationship, :treatment, :keep, :additional, :pickable, :not_pickable_reason)
    end
end

app/helpers/trees_helper.rb
module TreesHelper
end

app/views/trees/_formlist.html.erb
<table>
  <thead>
    <tr>
    <th style="width: 20px"></th>
      <th style="width: 20px"></th>
      <th style="width: 30%">Species</th>
      <th style="width: 70%">Address</th>
    </tr>
  </thead>

  <tbody>
    <% @trees.each do |tree| %>
      <tr>
        <td>
          <%= check_box_tag  "event[tree_ids][]", tree.id %>     
        </td>
        <td>
          <% if tree.species.present? %>
            <% if Tree.types.include?(tree.species.capitalize.to_s) %>
              <%= image_tag("fruits/#{tree.species.downcase}16.png") %>
            <% end %>
          <% end %>
        </td>
        <td>
          <%= tree.species %>
        </td>
        <td><%= (tree.owner.address.split(/[\n,]+/)[0]).to_s + "..." %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= paginate @trees %>

app/views/trees/_list.html.erb
<ul id="tree_list">
    <% @trees.each do |tree| %>
      <li>
        <div style="width: 25px; clear: none; float: left; padding-left: 10px">
          <% if tree.species.present? %>
            <% if Tree.types.include?(tree.species.capitalize.to_s) %>
              <%= image_tag("fruits/#{tree.species.downcase}16.png") %>
            <% else %>
              &nbsp;
            <% end %>
            <% else %>
              &nbsp;
          <% end %>
          
        </div>
        <div style="width: 30%; clear: none; float: left">
          <%= link_to tree.species, tree %>
        </div>
        <div style="width: 30%; clear: none; float: left">
            <%= link_to (tree.owner.address.split(/[\n,]+/)[0]).to_s + "...", tree %></td>
        </div>
        <div style="clear: none; float: left">
          <%= link_to "Schedule #{Configurable.event.titlecase}", new_event_path(tree_id: tree.id), {class: "button"} %>
        </div>
      </li>
    <% end %>
</ul>

<br>
<%= paginate @trees %>

app/views/trees/_mylist.html.erb
<div style="float: right">
  <%= link_to 'Add New Tree', new_tree_path, {class: 'button blue'} %>
</div>
<ul id="tree_list">
    <% trees.each do |tree| %>
      <li>
        <div style="width: 25px; clear: none; float: left; padding-left: 10px">
          <% if tree.species.present? %>
            <% if Tree.types.include?(tree.species.capitalize.to_s) %>
              <%= image_tag("fruits/#{tree.species.downcase}16.png") %>
            <% else %>
              &nbsp;
            <% end %>
            <% else %>
              &nbsp;
          <% end %>
          
        </div>
        <div style="width: 30%; clear: none; float: left">
          <%= link_to tree.species, tree %>
        </div>
        <% if tree.owner.address.present? %>
          <div style="width: 30%; clear: none; float: left">
              <%= link_to (tree.owner.address.split(/[\n,]+/)[0]).to_s + "...", tree %></td>
          </div>
        <% end %>
      </li>
    <% end %>
</ul>

app/views/trees/edit.html.erb
<h1>Editing tree</h1>

<%= render 'form' %>

<%= link_to 'Show', @tree %> |
<%= link_to 'Back', trees_path %>

app/views/trees/index.html.erb
<h1>Listing trees</h1>

<div style="float: right">
	<%= link_to 'Add New Tree', new_tree_path, {class: 'button blue'} %>
</div>

<div style="float: left">	
	<%= form_tag trees_path, method: :get do %>
	  <b>Search </b> <%= text_field_tag :q, @q, placeholder: 'species or address' %>
	  <%= submit 'Search' %>
	<% end %>
</div>

<%= render 'list' %>

app/views/trees/mine.html.erb
<% if @isowner.any? %>
	<h1>Trees I Own</h1>
	<%= render 'mylist', trees: @isowner %>
<% end %>

<% if @issubmitter.any? %>
	<h1>Trees I Submitted</h1>
	<%= render 'mylist', trees: @issubmitter %> 
<% end %>

<% if !@issubmitter.any? && !@isowner.any? %>
 You have not yet added a tree to the tree directory. Why not add one now?
  <%= link_to "Add a Tree", new_tree_path(), {class: "button"} %>
<% end %>

app/views/trees/new.html.erb
<h1>New tree</h1>

<%= render 'form' %>

<%= link_to 'Back', trees_path %>

app/views/trees/show.html.erb
	<h1 class="title">	
	<% if Tree.types.include?(@tree.species.capitalize.to_s) %>
		<%= image_tag("fruits/#{@tree.species.downcase}32.png") %>
	<% end %>
	A beautiful <b><%= @tree.species.capitalize %></b></h1>
	<h2 class="title">at <%= @tree.owner.address %></h2>

<div id="tree_details" class="block">
	<h1>Tree Details</h1>

	<% if @tree.subspecies.present? %>
		<p>
  			<b>Subspecies: </b> <%=@tree.subspecies %>
  		</p>
	<% end %>	
	<p>
  		<b>Height: </b> 
  			<% if @tree.height.present? %>
  				<%=Tree.height_labels.key(@tree.height.to_sym) %>
  			<% else %>
  				Unknown
  			<% end %>
  	</p>
	<% if @tree.treatment.present? %>
		<p>
  			<b>Treatment: </b> <%=@tree.treatment %>
  		</p>
	<% end %>
	<% if @tree.additional.present? %>
		<p>
  			<b>Additional Notes: </b> <%=@tree.additional %>
  		</p>
	<% end %>
	<% if !@tree.pickable.nil? %>
		
		<p>
		<% if @tree.pickable == true %>
  			This tree is pickable.
  		<% else %>
  			<b style="color: #ff0000">This tree is not pickable.</b><br />
  			<b>Reason:</b><br />
  			<% if @tree.not_pickable_reason.present? %>
  				<%=@tree.not_pickable_reason %>
  			<% end %>		
  		<% end %>
  		</p>
	<% end %>  	
	<% if @tree.ripen.present? %>
		<p>
  			<b>This tree ripens close to: </b> <%=date(@tree.ripen) %>
  		</p>
	<% end %>



</div>



<div id="contact_information" class="block">
	<h1>Contact Information</h1>
	<%
		if @tree.submitter_id.present?
			contact = @tree.submitter
		else 
			contact = @tree.owner
		end
	 %>


	<%= start_cols %>
		<p>
			<b>Name: </b> <%= contact.fname %> <%= contact.lname %> is the primary contact for this tree.
		</p>
		<p>
			<b>Contact Type: </b> They are the <%=Tree.relationship_labels[@tree.relationship.to_sym] %>
		</p>
		<p>
			<b>Email: </b> <%= contact.email || "None" %> 
		</p>
		<p>
			<b>Phone: </b> <%= contact.phone %>
		</p>
		<p>
			<b>Mailing Address: </b> <%= contact.address %>
		</p>
		<p>
			<b>Contact Info: </b> <%= contact.contactnotes || "None" %>
		</p>

	<%= next_col %>
		You can contact this person by:
		<ul>
		<% if contact.can_email.present? %>
			<% if contact.can_email == true %> 
				<li>Email</li>
			<% end %>
		<% else %>
			<li>Email</li>
		<% end %>
		<% if contact.can_phone.present? %>
			<% if contact.can_phone == true %> 
				<li>Phone</li>
			<% end %>
		<% else %>
			<li>Phone</li>
		<% end %>
		<% if contact.can_mail.present? %>
			<% if contact.can_mail == true %> 
				<li>Mail</li>
			<% end %>
		<% else %>
			<li>Mail</li>
		<% end %>
		<% if contact.do_not_contact_reason.present? %>
			<p style="color: #ff0000"> Do not contact this person!</p>
				<% if current_user.has_role?(:admin) %>
					Because: <%=contact.do_not_contact_reason %>
				<% else %>
					If you need to know why, ask admin.
				<% end %>
		<% end %>
	<%= end_cols %>
	<!-- Add contact instructions -->



</div>



<div id="tree_event" class="block">


<h1>
	Event Details   

	<div style="float: right">
	<% if can? :create, Event %>
    	<%= link_to "Add New #{Configurable.event.titlecase} for this Tree", new_event_path({"tree_id" => @tree.id}), {class: "button"} %>
  	<% end %>
  	</div>

  </h1>
  <p>
  	<b>Tree Address: </b><%=@tree.owner.address %>
  </p>
  <p>
  	<b>Ward: </b><%=@tree.owner.ward %>
  </p>

 <h1>Event Instructions</h1>
	<% if @tree.keep.present? %>
		<p>Keep <b><%= Tree.keep_result_labels.key(@tree.keep.to_sym) %></b> of the fruit for the property owner.</p>
	<% end %>

	<b>Tree Access Notes: </b>
	<p><%= @tree.owner.propertynotes %></p>

	<% @tree.owner.ladder = User.ladders[:yes] %>

	<% if @tree.owner.ladder.present? %>
	<p>Ladder: <b>The property owner <%=User.ladder_show_labels.key(@tree.owner.ladder.to_sym) %></b></p>
	<% end %>



	<h3>Treatment</h3>
	<p><%= @tree.treatment %></p>

	<h3>Additional Notes</h3>
	<p><%= @tree.additional %></p>

</div>

<% if @events.any? %>

<div id="previous_tree_events" class="block">
	<h1>Events with this Tree</h1>
	<ul>
	<% @events.each do |et| %>
      <li>
        <%=et.event.name %> 
        - 
        <% if et.event.start.present? %> 
        	<%=date(et.event.start).to_s %> 
        	at <%=time(et.event.start).to_s %> 
        <% else %>
        	<i>(Date not yet set)</i>
        <% end %>

        <% if et.event.event_trees.count > 1 %> - with <%=(et.event.event_trees.count -1).to_s %> other trees <% end %>
      </li>
    <% end %>
    </ul>
</div>
<% end %>


  <% if can? :create, Event %>
    <%= link_to "Add New #{Configurable.event.titlecase} for this Tree", new_event_path({"tree_id" => @tree.id}) %> |
  <% end %>
  	<%= link_to 'Add a new tree with this location', copy_location_tree_path(@tree) %> |
  	<%= link_to 'Add a new tree exactly like this', copy_tree_path(@tree) %> |
	<%= link_to 'Edit', edit_tree_path(@tree) %> |
    <%= link_to 'Delete', @tree, method: :delete, data: { confirm: 'Are you sure?' } %> |
	<%= link_to 'Back', trees_path %>