config/routes.rb
Epm::Application.routes.draw do

  resources :agencies

  resources :equipment_sets

  root 'events#dashboard'

  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    resources :roles, only: [:create, :destroy], shallow: true
    get 'map', on: :collection
    patch 'deactivate', on: :member
    get 'invite'
  end
  get 'me', to: 'users#me'
  get 'my_wards', to: 'users#my_wards'

  resources :events do
    get 'calendar', on: :collection
    get 'dashboard', on: :collection
    member do
      get 'who'
      get 'cancel', to: 'events#ask_to_cancel'
      patch 'cancel'
      patch 'approve'
      patch 'claim'
      patch 'unclaim'
      patch 'attend'
      patch 'unattend'
      patch 'invite'
      patch 'take_attendance'
    end
  end

  # for configurable_engine gem; it generates its own routes as well which are unused
  put 'settings', to: 'settings#update', as: 'settings'
  get 'settings', to: 'settings#show'

  resources :trees do
    get 'copy', on: :member
    get 'copy_location', on: :member
    get 'mine', on: :collection
    get 'closest', on: :collection
  end   

  get 'geocode', to: 'geocode#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :event_trees
  belongs_to :equipment_set
  belongs_to :agency
  has_many :trees, :through => :event_trees 
  accepts_nested_attributes_for :event_trees
  strip_attributes

  def self.csv(events)
    # exports events; adds info for number of people for each event user status, i.e. how many attended, how many were waitlisted, etc.
    CSV.generate force_quotes: true do |csv|
      eu_statuses = EventUser.statuses.keys.map{|s| "#{Configurable.participant.pluralize} #{s}"}
      csv << ['id', 'name', 'status', 'created', 'updated', 'start', 'finish', 'description', 'notes', Configurable.coordinator, 'address', "min #{Configurable.participant.pluralize}", "max #{Configurable.participant.pluralize}"] + eu_statuses
      events.each do |event|
        row = [event.id, event.name, event.status, event.created_at, event.updated_at, event.start, event.finish, event.description, event.notes, event.coordinator ? event.coordinator.display_name : nil, event.address, event.min, event.max]
        eus = event.event_users.group('event_users.status').count
        EventUser.statuses.each{|status, status_id| row << (eus[status_id] || 0) }
        csv << row
      end
    end
  end

  def coordinator_id=(val)
    # this was needed due to radio button converting 'nil' value to 'on' to 0
    val = nil unless val.to_i > 0
    super val
  end

  def changed_significantly?
    # todo: remove lat+lng from this and test separataly via removal or addition of coords or distance change > n
    ['start', 'finish', 'name', 'description', 'address', 'lat', 'lng'].each do |attr|
      return true if self.send(attr) != prior[attr]
    end
    false
  end

  attr_accessor :prior
  def track
    self.prior = attributes
    ['past?', 'awaiting_approval?'].each do |meth|
      self.prior[meth] = send(meth)
    end
  end

  enum status: [:proposed, :approved, :cancelled]

  def can_edit_attribute?(attribute, user)
    return false unless user.ability.can?(:edit, self)
    return true if user.has_role?(:admin)
    return true if user.has_role?(:coordinator) && ((coordinator.present? && coordinator == user) || coordinator.blank?)
    return false unless [:start, :finish].include?(attribute)
    #proposed? || start.blank?
  end

  def can_edit_something?(user)
    [:name, :start, :finish, :notes, :description, :address, :lat, :lng, :ward, :hide_specific_location, :min, :max, :coordinator].each do |attr|
      return true if can_edit_attribute? attr, user
    end
    false
  end

  validate :must_not_be_empty
  def must_not_be_empty
    if start.blank? && name.blank? && description.blank? && address.blank? && !coords
      errors.add(:base, 'An event must have a name, description, date, or address')
    end
  end

  validate :must_start_before_finish
  validates :finish, presence: true, if: "start.present?"
  def must_start_before_finish
    if start.present? && finish.present? && start > finish
      errors.add(:finish, 'must be after the start')
    end
  end

  before_validation do |event|
    event.finish = nil if event.start.blank?
    # don't allow saving with only one of lat, lng; must be neither or both
    event.lat = nil if event.lng.blank?
    event.lng = nil if event.lat.blank?
  end

  def min=(val)
    val = 0 if val.blank?
    super(val)
  end
  validate :max_must_be_at_least_min
  def max_must_be_at_least_min
    if max.present? && max < min
      errors.add(:max, 'must be greater than the minimum, or blank')
    end
  end

  belongs_to :ward

  # allow for adding a reason for cancelling an event, with separate fields for admin/coordinator and participants
  attr_accessor :cancel_notes, :cancel_description
  def cancel_notes=(str)
    str = str.strip unless str.nil?
    if str.present?
      self.notes = "Cancelled because: #{str}\n\n#{notes}".strip
      @cancel_notes = str
    end
  end
  def cancel_description=(str)
    str = str.strip unless str.nil?
    if str.present?
      self.description = "Cancelled because: #{str}\n\n#{description}".strip
      @cancel_description = str
    end
  end
  def cancel(reasons = {})
    update reasons.merge(status: :cancelled)
    Invitation.where(event_id: id).destroy_all
  end

  has_many :event_users, dependent: :destroy
  has_many :participants, -> { where 'event_users.status' => EventUser.statuses_array(:attending, :attended) }, through: :event_users, source: :user
  has_many :waitlisted, -> { where('event_users.status' => EventUser.statuses[:waitlisted]).order('event_users.updated_at') }, through: :event_users, source: :user
  has_many :no_shows, -> { where 'event_users.status' => EventUser.statuses['no_show'] }, through: :event_users, source: :user
  belongs_to :coordinator, class_name: 'User'
  def users # i.e. participants and the coordinator
    people = participants.to_a
    people << coordinator if coordinator
    people
  end

  # this section identical to that in model user.rb
  acts_as_mappable
  attr_accessor :no_geocode # force geocoding to not happen. used for testing
  after_validation :geocode, if: "!no_geocode && address_changed? && address.present? && (lat.blank? || lng.blank?)"
  validates :lat, numericality: {greater_than_or_equal_to: -90, less_than_or_equal_to: 90}, allow_nil: true
  validates :lng, numericality: {greater_than_or_equal_to: -180, less_than_or_equal_to: 180}, allow_nil: true

  default_scope { order :start }
  scope :with_date, -> { where 'start IS NOT NULL AND finish IS NOT NULL' }
  scope :past, -> { where('finish < ?', Time.zone.now).reorder('finish DESC') }
  scope :not_past, -> { where 'start IS NULL OR finish > ?', Time.zone.now }
  scope :participatable_by, ->(user) { # checks user for participatablility, assumed already checking that the events for participatability
    where.not("id IN (SELECT event_id FROM event_users WHERE user_id = ? AND status IN (?))", user.id, EventUser.statuses_array(:attending, :waitlisted, :requested, :denied))
      .where.not(coordinator_id: user.id)
      .distinct
  }
  scope :coordinatorless, -> { where coordinator: nil }
  scope :dateless, -> { where start: nil }
  #scope :byStatus -> (listofstatuses) { where(status: listofstatuses) }
  scope :participatable, -> { where.not(start: nil).where.not(coordinator_id: nil).where('events.status = ?', statuses[:approved]) }
  scope :not_cancelled, -> { where 'events.status != ?', statuses[:cancelled] }
  scope :awaiting_approval, -> { not_past.where 'events.status = ? AND coordinator_id IS NOT NULL AND start IS NOT NULL', statuses[:proposed] }
  scope :needing_participants, -> { participatable.not_past.where(below_min: true) }
  scope :accepting_participants, -> { participatable.not_past.where(reached_max: false) }
  scope :accepting_not_needing_participants, -> { accepting_participants.where(below_min: false) }
  scope :needing_attendance_taken, -> { participatable.past.joins("INNER JOIN event_users ON event_users.event_id = events.id AND event_users.status = #{EventUser.statuses[:attending]}").distinct }
  scope :in_month, ->(year, month) { # can pass in integers or strings which are integers
    month ||= ''
    year ||= ''
    unless (1..12).include?(month.to_i) && year.to_s.length == 4
      month = Time.zone.now.month
      year = Time.zone.now.year
    end
    start = Time.zone.parse "#{year}-#{month}-01"
    finish = month.to_i < 12 ? start.change(month: (start.month + 1)) : start.change(month: 1, year: (start.year + 1))
    where("start >= ? AND start < ?", start, finish)
  }
  scope :will_happen_in_two_days, -> {
    next_day = Time.zone.now + 1.day
    participatable.where('start > ? AND start < ?', next_day, (next_day + 1.day))
  }

  attr_reader :start_day, :start_time_12, :start_time_p
  attr_accessor :time_error
  before_validation do |event|
    errors.add(:start_time_12, 'Start time must be in the format ##:##') if event.time_error
    # todo. this should be added to start_time_12 rather than :base, but that's no good as "start time 12" is a poor name for users. fix
  end
  def assign_attributes(attrs)
    # if inputing start in parts (day and time), then combine them
    start_day = attrs.delete(:start_day)
    start_time = attrs.delete(:start_time_12)
    if start_time.present? && !(start_time.strip =~ /1?[0-9](:[0-9]{2})?/)
      start_time = nil
      self.time_error = true
    end
    start_time_p = (attrs.delete(:start_time_p) || 'AM').upcase.gsub('.', '')
    attrs[:start] = "#{start_day} #{start_time} #{start_time_p}" if attrs[:start].blank? && start_day.present? && start_time.present?
    # this is needed because during mass assignment, we can't guarantee that :start will be set before :duration
    dur = attrs.delete(:duration)
    super(attrs)
    self.duration = dur
  end
  def start_time_12 # start time using 12-hour clock
    start.present? ? start.strftime('%l:%M').strip : nil
  end
  def start_time_p
    start.present? ? start.strftime('%p') : nil
  end
  def duration=(timespan)
    if start.present? && timespan.present? && timespan.to_i > 0
      self.finish = start + timespan.to_i
    else
      nil
    end
  end
  def duration
    (start.present? && finish.present?) ? (finish - start).round : nil
  end
  def duration_hours
    duration.present? ? (duration / 3600) : nil
  end
  def self.default_time
    '5:00 PM'
  end

  def past?
    finish.present? ? finish < Time.zone.now : nil
  end
  def time_until
    start.present? ? start - Time.zone.now : nil
  end
  def hours_until
    start.present? ? (time_until / 1.hour).round : nil
  end

  def awaiting_approval?
    !past? && proposed? && coordinator && start
  end

  include ActionView::Helpers::TextHelper # needed for truncate()
  def display_name(user = nil)
    return name if name.present?
    return truncate(description, length: 50, separator: ' ') if description.present?
    if address.present? && (!hide_specific_location || (user && user.ability.can?(:read_specific_location, self)) )

app/helpers/events_helper.rb
module EventsHelper

  def event_user_status s
    event_user_statuses = {
      invited: "Invited",    
      requested: "Requested",     
      attending: "Attending",   
      not_attending: "Not Attending", 
      waitlisted: "Waitlisted",    
      denied: "Denied",        
      withdrawn: "Withdrawn",     
      cancelled: "Cancelled",     
      attended: "Attended",      
      no_show: "No Show"        
    }
    event_user_statuses[s.to_sym]
  end

  def date(datetime)
    # this method needs to be kept in synch with js-formatted date in events/_form.html.erb
    datetime.strftime '%A %B %e, %Y'
  end

  def time(datetime)
    datetime.strftime('%l:%M %p').strip
  end

  def relative_time(event)
    str = time_ago_in_words event.start
    event.past? ? "#{str} ago" : "in #{str}"
  end

  def month_calendar(events)
    html_options = { class: 'month_calendar' }
    html_options[:data] = { map: true } if events.find{|e|e.coords}
    content_tag 'section', html_options do
      # calls method from simple_calendar gem with particular options
      options = {
        time_selector: 'start',
        class: nil,
        prev_text: '«<span> prev<span>ious</span></span>'.html_safe,
        next_text: '<span>next </span>»'.html_safe
      }
      if can? :create, Event
        add_link = lambda{ |date| link_to '+', new_event_path(start_day: date), class: 'add', title: "add #{Configurable.event} on this day" }
        options[:empty_date] = add_link
        options[:not_empty_date] = add_link
      end
      calendar events, options do |event|
        yield(event)
      end
    end
  end

end

# overriding header method for calendar so that we can insert the number of events during that month
# for now relies on using instance variable @events
# original: https://github.com/excid3/simple_calendar/blob/master/lib/simple_calendar/view_helpers.rb
module SimpleCalendar
  module ViewHelpers
    def month_header(selected_month, options)
      content_tag :h2 do
        previous_month = selected_month.advance :months => -1
        next_month = selected_month.advance :months => 1
        tags = []
        tags << month_link(options[:prev_text], previous_month, options[:params], {:class => "previous-month"})
        tags << "#{I18n.t("date.month_names")[selected_month.month]} #{selected_month.year} &ndash; #{pluralize @events.length, Configurable.event.titlecase}"
        tags << month_link(options[:next_text], next_month, options[:params], {:class => "next-month"})
        tags.join.html_safe
      end
    end
  end
end

app/views/events/_events.html.erb
<ol class="unordered">
  <% events.each do |event| %>
    <% coords = event.coords(current_user) %>
    <li<%= " data-lat=\"#{coords[0]}\" data-lng=\"#{coords[1]}\"".html_safe if coords %>>
      <%= link_to event.display_name(current_user), event %>
      <% if event.start.present? %>
        <small><%= relative_time event %></small>
      <% end %>
    </li>
  <% end %>
</ol>

app/views/events/ask_to_cancel.html.erb
<% title "Cancel or Delete ‘#{@event.display_name(current_user)}’" %>


<%= form_for @event, url: cancel_event_path(@event), method: :patch do |f| %>

  <h2>Cancel</h2>

  <p>You may optionally enter in a reason for cancellation.</p>

  <div class="field">
    <%= f.label :cancel_description, 'Reason' %><br>
    <%= f.text_area :cancel_description %>
  </div>

  <div class="field">
    <%= f.label :cancel_notes, 'Reason &ndash; shown only to Admins and Coordinator'.html_safe %><br>
    <%= f.text_area :cancel_notes %>
  </div>

  <%= cancel 'Do Not Cancel' %>
  <%= submit "Cancel #{Configurable.event.titlecase}", class: 'danger' %>

<% end %>

<% if can? :destroy, @event %>

  <%= form_for @event, url: event_path(@event), method: :delete, html: {style: "margin-top:4em"} do |f| %>

    <h2>Delete</h2>

    <%= submit "Permanently Delete #{Configurable.event.titlecase}", class: 'danger', data: {confirm: "Delete ‘#{@event.display_name(current_user)}’? This cannot be undone."} %>

  <% end %>
<% end %>

app/views/events/calendar.html.erb
<% title "#{Configurable.event.pluralize.titlecase} by Month" %>

<% now = Time.zone.now %>
<% if params['month'].present? && !(params['month'].to_i == now.month && params['year'].to_i == now.year) %>
  <% content_for :header do %>
    <%= link_to "Back to #{now.strftime('%B, %Y')}", calendar_events_path %>
  <% end %>
<% end %>

<%= month_calendar @events do |event| %>
  <% if can? :show, event %>
    <%
      ops = { class: 'event' }
      coords = event.coords(current_user)
      ops[:data] = {lat: coords[0], lng: coords[1], popup: true} if coords
    %>
    <%= link_to event.display_name(current_user), event, ops %>
  <% end %>
<% end %>

app/views/events/dashboard.html.erb
<% content_for :header  do %>
  <% if can? :calendar, Event %>
    <%= link_to 'Monthly Calendar', calendar_events_path %>
  <% end %>
  <% if can? :create, Event %>
    <%= link_to "Add New #{Configurable.event.titlecase}", new_event_path %>
  <% end %>
  <% if can? :export, Event %>
    <%= link_to "Export #{Configurable.event.pluralize.titlecase}", events_path(format: 'csv') %>
  <% end %>
<% end %>


<% if defined? @coordinators_not_taking_attendance %>
  <section id="coordinators_not_taking_attendance">
    <h2><%= Configurable.coordinator.pluralize.titlecase %> Not Taking Attendance</h2>
    <p><%= @coordinators_not_taking_attendance.map{|c| link_to c.display_name, c}.to_sentence.html_safe %>.</p>
  </section>
<% end %>

<%
  sections_shown = 0
  events_shown = 0
%>
<% @sections.each do |section| %>
  <% if section[:q].any? %>
    <%
      sections_shown += 1
      events_shown += section[:q].length
    %>
    <% section_id = section[:id] || section[:name].downcase.gsub(' ', '_') %>
    <%# these maps turned off for now %>
    <section id="<%= section_id %>"<%= ' data-map="side"'.html_safe if section[:q].find{|e|e.coords} && false %>>
      <h2><%= section[:name] %></h2>
      <%= render 'events', events: section[:q] %>
    </section>
  <% end %>
<% end %>

<%# not using toggle functionality for the time being %>
<% if false && sections_shown > 3 && events_shown > 20 %>
  <% content_for :js_ready do %>
    $('section').each(function(){
      $('<button title="minimize this section">-</button>')
        .prependTo($(this).children('h2'))
        .click(function(){
          $(this).parent().next().toggle();
          $(this).text($(this).text() == '-' ? '+' : '-');
          $(this).attr('title', $(this).attr('title').indexOf('min') ? 'minimize this section' : 'maximize this section');
        });
    });
  <% end %>
<% end %>

<%= content_tag(:p, "There are no #{Configurable.event.pluralize} to display.") if sections_shown.zero? %>

app/views/events/edit.html.erb
<% title "Edit #{Configurable.event.titlecase} ‘#{@event.display_name(current_user)}’" %>

<%= render 'form' %>

app/views/events/index.html.erb
<%= form_tag events_path, method: :get do %>
  <% content_for :js_ready do %>
    $('checkbox').change(function(){
      $(this).closest('form').submit();
    });
  <% end %>

  <% Event.statuses.each do | k, v| %>
    <%= check_box "statuses", k, checked: params['statuses'] ? params['statuses'][k] == "1" : false %>
    <%= label "statuses", k %>
  <% end %>
  <%= submit 'Search' %>
<% end %>

<% if @events.any? %>
  <%= render layout: 'events', locals: {events: @events, tag: 'li'} do %>
<% end %>
<% else %>
  <p>No events found.</p>
<% end %>

app/views/events/new.html.erb
<% title "New #{Configurable.event.titlecase}" %>

<%= render 'form' %>

app/views/events/show.html.erb
<%
  tit = @event.display_name(current_user)
  tit = "#{@event.status.capitalize}: #{tit}" unless @event.approved?
  title tit
%>

<% content_for :header do %>

  <% if can? :who, @event %>
    <%
      who_link = 'Who'
      unless @event.cancelled?
        who_link += "#{@event.past? ? ' Went' : '’s Coming'} (#{@event.users.length})"
      end 
    %>
    <%= link_to who_link, who_event_path(@event) %>
  <% end %>

  <%# this is duplicated in who.html.erb %>
  <% if can?(:claim, @event) && !@event.cancelled? && !@event.past? %>
    <%= link_to "Claim This #{Configurable.event.titlecase}", claim_event_path(@event), method: :patch %>
  <% elsif can?(:unclaim, @event) && @event.proposed? && @event.coordinator == current_user %>
    <%= link_to "Unclaim This #{Configurable.event.titlecase}", unclaim_event_path(@event), method: :patch %>
  <% end %>

  <% if can?(:take_attendance, @event) && @event.past? && @event.approved? && @event.event_users.where(status: EventUser.statuses[:attending]).any? %>
    <%= link_to 'Take Attendance', who_event_path(@event) %>
  <% end %>
  <% if @event.can_edit_something? current_user # needed as attributes have their own permissions %>
    <%= link_to 'Edit', edit_event_path(@event) %>
  <% end %>
  <% if can?(:approve, @event) && @event.proposed? %>
    <%= link_to 'Approve', approve_event_path(@event), method: :patch %>
  <% end %>
  <% if can?(:cancel, @event) && !@event.cancelled? %>
    <%= link_to 'Cancel or Delete', cancel_event_path(@event) %>
  <% end %>

<% end %>

<%= render 'rsvp' unless @event.cancelled? %>

<% if can?(:invite, @event) && @event.should_invite? %>
  <%= clear %>
  <div class="highlight">Please <%= button_to "Invite #{Configurable.participant.pluralize.titlecase}", invite_event_path(@event), method: :patch %>.</div>
<% end %>


<%= start_cols %>

<p>
  <% if @event.start %>
    <%= date @event.start %> <small><%= relative_time @event %></small>
    <br>
    <%= time @event.start %> to <%= time @event.finish %>
    <small>for <%= pluralize @event.duration_hours, 'hour' %></small>
  <% else %>
    No date set.
  <% end %>
</p>

<% if @event.notes.present? && can?(:read_notes, @event) %>
  <div id="notes">
    <strong>Notes for <%= Configurable.admin.titlecase.pluralize %> and <%= Configurable.coordinator.titlecase %></strong>
    <%= paragraphs @event.notes %>
  </div>
<% end %>

<% if @event.equipment_set.present? %>
  Equipment Set : <%= link_to @event.equipment_set.title, @event.equipment_set %>
<% end %>

<% if @event.agency.present? %>
  <div>Agency : <%= link_to @event.agency.title, @event.agency %></div>
<% end %>

<%= paragraphs @event.description if @event.description.present? %>




<% if @event.trees.any? %>
<h3>Trees for this Pick</h3>  
<div id="selectedTrees" style="width: 100%">
<table>
  <thead>
    <tr>
      <th colspan="2">Species</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <tr class="selectedTree"></tr>
  <% @event.event_trees.each do |et| %>
    <tr class="selectedTree">
      <td>
        <% if et.tree.species.present? %>
          <% if Tree.types.include?(et.tree.species.capitalize.to_s) %>
            <%= image_tag("fruits/#{et.tree.species.downcase}32.png") %>
          <% end %>
        <% end %>
      </td>
      <td>
        <%= et.tree.species %>
      </td>
      <td><%= et.tree.owner.address %></td>

    

    </tr>
  <% end %>
    </tbody>
</table>
</div>
<% end %>






<%= next_col unless @event.description.blank? && @event.start.blank? && (@event.notes.blank? || cannot?(:read_notes, @event)) %>

<%= render 'shared/address_and_map', thing: @event %>

<%= end_cols %>

app/views/events/who.html.erb
<%
  tit = 'Who'
  if @event.cancelled?
    tit += ' Would Have Come'
  else
    tit += @event.past? ? ' Went' : '’s Coming'
  end
  title "#{tit} to ‘#{@event.display_name(current_user)}’"
%>

<% content_for :header do %>
  <%= link_to "#{Configurable.event.titlecase} Details", @event %>

  <%# this is duplicated in who.html.erb %>
  <% if can?(:claim, @event) && !@event.cancelled? && !@event.past? %>
    <%= link_to "Claim This #{Configurable.event.titlecase}", claim_event_path(@event), method: :patch %>
  <% elsif can?(:unclaim, @event) && @event.proposed? && @event.coordinator == current_user %>
    <%= link_to "Unclaim This #{Configurable.event.titlecase}", unclaim_event_path(@event), method: :patch %>
  <% end %>

  <%= link_to('Edit Attendance', take_attendance: true) if @can_take_attendance && !@taking_attendance %>
<% end %>


<% if @taking_attendance %>
  <%= form_for @event, url: take_attendance_event_path(@event), method: :patch do |f| %>
    <fieldset class="users">
      <legend>Attendance</legend>
      Check those who attended.
      <% @event.event_users.where(status: EventUser.statuses_array(:attending, :attended, :no_show)).each do |eu| %>
        <label>
          <%= check_box_tag "attendance[#{eu.id}]", true, eu.attended? %>
          <%= render 'users/user', user: eu.user %>
        </label>
      <% end %>
    </fieldset>
    <%= submit 'Take Attendance' %>
  <% end %>
  <% content_for :js_ready do %>
    $('fieldset.users label:first')
      .before('<br>')
      .before($('<button type="button" class="default">Check All</button>').click(function(){
          $('fieldset.users input').prop('checked', true);
        })
      );
  <% end %>
<% end %>

<%# no need to tell coordinators they're attending, as they are listed already, right after this %>
<%= render('rsvp') unless (@event.coordinator == current_user) || @event.cancelled? %>

<% if @show_invites || @show_invite %>
  <section>
    <h2>Invitations</h2>
    <% if @num_invited > 0 %>
      <p><%= pluralize @num_invited, 'invitation' %> <%= 'is'.pluralize(@num_invited) %> awaiting a response (<%= Invitation.where(event_id: @event.id).count %> unsent).</p>
    <% end %>
    <% if @num_declined > 0 %>
      <p><%= pluralize @num_declined, 'invitation' %> <%= 'was'.pluralize(@num_declined) %> declined.</p>
    <% end %>
    <%= button_to("Invite #{Configurable.participant.pluralize.titlecase}", invite_event_path(@event), method: :patch) if @show_invite %>
<% end %>

<section>
  <h2><%= Configurable.coordinator.titlecase %></h2>
  <% if @event.coordinator %>
    <%= render 'users/user', user: @event.coordinator %>
  <% else %>
    None set.
  <% end %>
</section>


<% if @event.can_have_participants? && !@taking_attendance %>

  <section id="participants">
    <h2>
      <%= pluralize @event.participants.count, Configurable.participant.titlecase %>
      <% if @event.can_accept_participants? %>
        &ndash;
        <% if @event.participants_needed > 0 %>
          <%= @event.participants_needed %> More Needed
        <% elsif @event.full? %>
          Full
        <% else %>
          <%
            spots = @event.remaining_spots
            spots = 'Unlimited' if spots == true
          %>
          <%= pluralize spots, 'Spot' %> Left
        <% end %>
      <% end %>
    </h2>
    <% if @event.participants.any? %>
      <%= render 'users/users', users: @event.participants %>
    <% else %>
      <p>None<%= ' yet' if !@event.past? %>.</p>
    <% end %>
  </section>

  <% if @event.no_shows.any? %>
    <section id="no_show_participants">
      <h2><%= pluralize @event.no_shows.count, "Absent #{Configurable.participant.titlecase}" %></h2>
      <%= render 'users/users', users: @event.no_shows %>
    </section>
  <% end %>

  <% if (current_user.has_role?(:admin) || current_user == @event.coordinator) && @event.approved? && !@event.past? && @event.waitlisted.any? %>
    <section id="waitlisted">
      <h2><%= @event.waitlisted.count %> Waitlisted</h2>
      <%= render 'users/users', users: @event.waitlisted %>
    </section>
  <% end %>

<% end %>