config/routes.rb
Epm::Application.routes.draw do

  resources :agencies

  resources :equipment_sets

  root 'events#dashboard'

  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    resources :roles, only: [:create, :destroy], shallow: true
    get 'map', on: :collection
    patch 'deactivate', on: :member
    get 'invite'
  end
  get 'me', to: 'users#me'
  get 'my_wards', to: 'users#my_wards'

  resources :events do
    get 'calendar', on: :collection
    get 'dashboard', on: :collection
    member do
      get 'who'
      get 'cancel', to: 'events#ask_to_cancel'
      patch 'cancel'
      patch 'approve'
      patch 'claim'
      patch 'unclaim'
      patch 'attend'
      patch 'unattend'
      patch 'invite'
      patch 'take_attendance'
    end
  end

  # for configurable_engine gem; it generates its own routes as well which are unused
  put 'settings', to: 'settings#update', as: 'settings'
  get 'settings', to: 'settings#show'

  resources :trees do
    get 'copy', on: :member
    get 'copy_location', on: :member
    get 'mine', on: :collection
    get 'closest', on: :collection
  end   

  get 'geocode', to: 'geocode#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="no-js">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title><%= Configurable.title %><%= ": #{yield :title}" if content_for :title %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <% if content_for? :js_ready %>
    <script type="text/javascript">
      $(function(){<%= yield :js_ready %>});
    </script>
  <% end %>

  <%# metadata etc here copied from source of http://notfarfromthetree.org/ %>
  <link rel="apple-touch-icon" href="http://notfarfromthetree.org/nfftt_2014/wp-content/themes/nfftt/library/images/apple-icon-touch.png">
  <link rel="icon" href="http://notfarfromthetree.org/nfftt_2014/wp-content/themes/nfftt/favicon.png?v=2">
  <!--[if IE]>
  <link rel="shortcut icon" href="http://notfarfromthetree.org/nfftt_2014/wp-content/themes/nfftt/favicon.ico">
  <![endif]-->
  <meta name="msapplication-TileColor" content="#f01d4f">
  <meta name="msapplication-TileImage" content="http://notfarfromthetree.org/nfftt_2014/wp-content/themes/nfftt/library/images/win8-tile-icon.png">

  <%= csrf_meta_tags %>
</head>
<body
  class="<%= controller_name %>-<%= params[:action] %>"
  data-lat="<%= (user_signed_in? ? current_user.lat : nil) || 43.7 %>"
  data-lng="<%= (user_signed_in? ? current_user.lng : nil) || -79.4 %>"
  >

  <div id="preheader">
   <div id="logo_bg"></div>
   <a id="logo" href="http://notfarfromthetree.org/"><img src="http://notfarfromthetree.org/nfftt_2014/wp-content/themes/nfftt/library/images/nfftt_logo.png" height="179" width="310" alt="Not Far From The Tree logo" /></a>
   <h1><%= link_to Configurable.title, root_path %></h1>
  </div>

  <header>
    <% if user_signed_in? %>
      <nav>
        <ul>
          <li<%= ' class="active"'.html_safe if controller_name == 'events' %>><%= link_to Configurable.event.pluralize.titlecase, root_path %></li>
          <% on_profile = controller_name == 'users' && params['id'].to_i == current_user.id %>
          <% if can? :index, User %>
              <li<%= ' class="active"'.html_safe if controller_name == 'users' && !on_profile %>><%= link_to 'Users', users_path %></li>
          <% end %>
          <% if can? :show, :setting %>
            <li<%= ' class="active"'.html_safe if controller_name == 'settings' %>><%= link_to 'Settings', settings_path %></li>
          <% end %>
          <li<%= ' class="active"'.html_safe if on_profile %>><%= link_to 'My Profile', current_user %></li>
          
          <% if false %>
          <li<%= ' class="active"'.html_safe if controller_name == 'trees' && action_name == 'mine' %>><%= link_to 'My Trees', mine_trees_path %></li>
          <% end %>
          <% if false #can? :index, Tree %>
            <li<%= ' class="active"'.html_safe if controller_name == 'trees' && action_name != 'mine'%>>
              <%= link_to 'Trees', trees_path %>
            </li>
          <% end %>
          <% if can? :index, EquipmentSet %>
            <li<%= ' class="active"'.html_safe if controller_name == 'equipment_sets'%>>
              <%= link_to 'Equipment Sets', equipment_sets_path %>
            </li>
          <% end %>
          <% if can? :index, Agency %>
            <li<%= ' class="active"'.html_safe if controller_name == 'agencies'%>>
              <%= link_to 'Agencies', agencies_path %>
            </li>
          <% end %>
        </ul>
        <%= link_to 'Log out', destroy_user_session_path, id: 'account' %>
      </nav>
    <% else %>
      <h1><%= link_to Configurable.title, root_path %></h1>
    <% end %>
    <%= clear %>
  </header>

  <% flash.each do |name, msg| -%>
    <%= content_tag :div, msg, class: name, id: 'flash' %>
  <% end -%>

  <% if content_for(:title) || content_for(:header) %>
    <div id="header">
      <%= content_tag(:h1, yield(:title)) if content_for :title %>
      <%= content_tag(:div, yield(:header)) if content_for :header %>
    </div>
  <% end %>

  <div id="main">
    <% if user_signed_in? && current_user.roles.none? %>
      <div class="highlight">Your account has been deactivated. For more information, please contact <%= mail_to 'info@notfarfromthetree.org' %> or call 647-774-7425.</div>
    <% end %>
    <%= yield %>
  </div>

</body>
</html>

app/views/layouts/event_mailer.html.erb
<%= yield %>

<%= paragraphs(Configurable.email_signature) if Configurable.email_signature.present? %>

<p>Visit <%= link_to 'your profile', me_url %> to change your email notifications by editing your city wards or to deactivate your account.</p>

app/views/layouts/event_mailer.text.erb
<%= yield %>

<%= Configurable.email_signature if Configurable.email_signature.present? %>

Visit your profile to change your email notifications by editing your city wards or to deactivate your account: <%= me_url %>